#!/bin/sh

branch="$(git rev-parse --abbrev-ref HEAD)"
validBranchRegex="^(feature|bugfix|revert|hotfix)\/[a-z0-9]+(-[a-z0-9]+)*$"

if [ "$branch" = "main" ]; then
  echo "You can't commit directly to master branch"
  exit 1
elif [[ ! $branch =~ $validBranchRegex ]]; then
  echo "$branch"
  echo "branch name violating default branch name rules: $validBranchRegex"
  exit 1
fi

exit 0
